### ISSUE TITLE
Please support  x86_64 arch

### ISSUE THREAD

**Issue by rzr** [intel/gbs#1]
Hi,

I planned to use gbs for building but it looks that my desired arch is not supported :

  error: arch x86_64 not supported, supported archs are:
  ia32,i686,i586,armv7hl,armv7el,armv7tnhl,armv7nhl,armv7l 

I checked in sources it is explicitly not in supported ones : 

  ./gbs/gitbuildsys/cmd_build.py:54:SUPPORTEDARCHS = [

Is there a reason for that ? or is it trivial to get it also working ?

Regards

**Comment by holagvk** [comment]
I think all platform packages need to be built first against x86_64 before you can build your own package for x86_64.

Right now, download.tizen.org/snapshots/ doesn't seem to have x86_64 built packages and that might be the reason x86_64 is not in the supported list of GBS.

**Comment by smcv** [comment]
This appears to be fixed in the gbs 0.12 rc1 pre-release: https://download.tizen.org/tools/pre-release/

(I don't know where the source code for that pre-release is tracked.)
